### ISSUE TITLE
Dataset Download URL not Working

### ISSUE THREAD

**Issue by anujdutt9** [mbrossar/denoise-imu-gyro#1]
Hi, 
Thanks for providing the code.
I am trying to download reformatted pickle format of the EuRoC and TUM-VI datasets from the URL that you have provided but the URL returns 404 Error.
Can you please provide the dataset files or a valid URL to get the files ?
Thanks.

**Comment by mbrossar** [comment]
Hello,

Sorry for the wrong link. Please find the corrected link:
[https://cloud.mines-paristech.fr/index.php/s/d2lHqzIk1PxzWmb/download](https://cloud.mines-paristech.fr/index.php/s/d2lHqzIk1PxzWmb/download)

**Comment by anujdutt9** [comment]
@mbrossar Thanks for providing the link. This link provides the data file.
Unfortunately, the model parameters link is also not working. Is it possible to provide that link as well ?
Thanks.

**Comment by volcanoh** [comment]
![image](https://user-images.githubusercontent.com/15354526/126477021-cb166894-0833-4f0a-b224-0536f1647f6f.png)
Hi, thanks for your code and datasets, however, I can not download any dataset. 
Do I need additional permissions for the dowload link? Or the URL is invalid again?

**Comment by mbrossar** [comment]
It seems that the cloud account of my folder university has been removed. 

Maybe if somebody yet has the files and can send them to me, I can add another link and solve that issue.

**Comment by volcanoh** [comment]
> It seems that the cloud account of my folder university has been removed. Maybe if somebody yet has the files and can send them to me, I can add another link and solve that issue. En 21 jul. 2021 12:52, en 12:52, Can HUANG ***@***.***> escribió:
> […](#)
> ![image](https://user-images.githubusercontent.com/15354526/126477021-cb166894-0833-4f0a-b224-0536f1647f6f.png) Hi, thanks for your code and datasets, however, I can not download any dataset. Do I need additional permissions for the dowload link? Or the URL is invalid again? -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#1 (comment)](https://github.com/mbrossar/denoise-imu-gyro/issues/1#issuecomment-884094388)

@anujdutt9 Could you give a hand?

**Comment by KleistvonLiu** [comment]
If possible I would also like to get the Datasets. Can anyone help?

**Comment by alun9258** [comment]
Did you solve this issue?
How can I get the dataset?wyilun@pku.edu.cn

**Comment by BahMoh** [comment]
Hey there,
yess I have solved this issue.
THe data itself:
https://github.com/BahMoh/TUMVI-IMU-only-Dataset-room1-to-room6
The fabricated code:
https://github.com/BahMoh/denoise-imu-gyro/tree/master

don't forget to give my github repo a star:)
