### ISSUE TITLE
dataset download link is unavailable

### ISSUE THREAD

**Issue by huazai665** [mbrossar/denoise-imu-gyro#11]
Hi,
wget "https://cloud.mines-paristech.fr/index.php/s/d2lHqzIk1PxzWmb/download" is error,  could you upload another available link? The link  of "https://cloud.mines-paristech.fr/index.php/s/OLnj74YXtOLA7Hv/download" is also unavailable, thanks.

**Comment by huazai665** [comment]
The link  of "https://cloud.mines-paristech.fr/index.php/s/OLnj74YXtOLA7Hv/download" is also available

**Comment by minje-KIM** [comment]
Hi, huazai665.
Did you solve this issue?
How can I get the dataset?

**Comment by alun9258** [comment]
Hi, huazai665.
Did you solve this issue?
How can I get the dataset?wyilun@pku.edu.cn

**Comment by INDEX108** [comment]
> Hi, wget "https://cloud.mines-paristech.fr/index.php/s/d2lHqzIk1PxzWmb/download" is error, could you upload another available link? The link of "https://cloud.mines-paristech.fr/index.php/s/OLnj74YXtOLA7Hv/download" is also unavailable, thanks.

Hi, huazai665.Have you obtained the dataset and pre training weights? How do I get it?1305919912@qq.com

**Comment by BahMoh** [comment]
Hi I regenerated the dataset just visit my github at:
https://github.com/BahMoh/denoise-imu-gyro
the code is working fine. Just you have to figure out the directories on
your machine.

Don't forget to give me a star.

**Comment by BahMoh** [comment]
Regarding the data itself you can look at:
https://github.com/BahMoh/TUMVI-IMU-only-Dataset-room1-to-room6
